<x-app-layout>
    <div class="student-home py-5 lg:h-[calc(100dvh-4.125rem)] lg:overflow-hidden">
        <div class="mx-auto max-w-none px-5 sm:px-8 lg:px-10 xl:px-12"><x-flash /></div>

        <div class="mx-auto grid max-w-none gap-5 px-5 sm:px-8 lg:h-full lg:grid-cols-[1.12fr_.88fr] lg:px-10 xl:px-12">
            <section class="dashboard-enter dashboard-enter-1 relative overflow-hidden rounded-[1.5rem] border border-brand-100 bg-[radial-gradient(circle_at_100%_0%,rgba(179,227,236,.8),transparent_38%),linear-gradient(135deg,#fff_0%,#f6fbff_58%,#eff7ff_100%)] p-6 shadow-xl shadow-ink-950/[.04] dark:border-white/10 dark:bg-[radial-gradient(circle_at_100%_0%,rgba(35,144,170,.3),transparent_38%),linear-gradient(135deg,#071b29,#0b1627)] sm:p-7 lg:min-h-0">
                <img src="{{ asset('images/ilastrasi_toga.png') }}" alt="Ilustrasi topi wisuda" class="pointer-events-none absolute bottom-24 right-0 hidden h-64 max-w-[48%] object-contain opacity-85 sm:block dark:opacity-50">
                <div class="relative flex h-full flex-col">
                    <span class="inline-flex w-fit items-center gap-2 rounded-lg bg-brand-50 px-3 py-1.5 font-mono text-[10px] font-bold uppercase tracking-[.14em] text-brand-600 dark:bg-brand-500/15 dark:text-brand-200"><x-heroicon-o-sparkles class="h-3.5 w-3.5" /> Ruang rekomendasi pribadi</span>
                    <div class="mt-5 max-w-[62%] sm:mt-6"><p class="text-sm text-ink-600 dark:text-porcelain-200/75">Selamat datang kembali,</p><h1 class="mt-1 font-display text-2xl font-extrabold uppercase leading-[1.12] tracking-tight text-ink-900 dark:text-porcelain-50 sm:text-3xl">{{ auth()->user()->name }}</h1><p class="mt-3 max-w-md text-sm leading-relaxed text-ink-600 dark:text-porcelain-200/75">Temukan program studi terbaik yang sesuai dengan minat, kemampuan, dan tujuan akademik Anda.</p></div>

                    <div class="mt-6 grid max-w-2xl gap-3 sm:grid-cols-2">
                        <article class="rounded-xl border border-brand-100 bg-white/90 p-4 shadow-sm shadow-ink-950/5 dark:border-white/10 dark:bg-white/[.06]"><div class="flex gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/15 dark:text-brand-200"><x-heroicon-o-document-check class="h-5 w-5" /></span><div class="min-w-0"><p class="font-mono text-[9px] font-bold uppercase tracking-[.14em] text-brand-600 dark:text-brand-200">Status saat ini</p>@if ($latest?->isCompleted())<p class="mt-1 text-[11px] text-ink-500 dark:text-porcelain-300/70">Rekomendasi terakhir Anda</p><p class="mt-1 text-sm font-bold leading-snug text-brand-600 dark:text-brand-200">{{ $latest->recommendedProgram?->full_name ?? 'Belum tersedia' }}</p>@elseif ($unfinished)<p class="mt-2 text-sm font-bold text-ink-800 dark:text-porcelain-100">Tes sedang berjalan</p>@else<p class="mt-2 text-sm font-bold text-ink-800 dark:text-porcelain-100">Siap memulai?</p>@endif</div></div></article>
                        <article class="rounded-xl border border-brand-100 bg-white/90 p-4 shadow-sm shadow-ink-950/5 dark:border-white/10 dark:bg-white/[.06]"><div class="flex gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/15 dark:text-brand-200"><x-heroicon-o-identification class="h-5 w-5" /></span><div><p class="font-mono text-[9px] font-bold uppercase tracking-[.14em] text-brand-600 dark:text-brand-200">Holland code terkuat</p><p class="mt-1 font-mono text-xl font-bold tracking-[.16em] text-brand-600 dark:text-brand-200">{{ $latest?->isCompleted() ? $latest->holland_code : 'RIASEC' }}</p><p class="mt-1 text-[11px] text-ink-500 dark:text-porcelain-300/70">Profil minat dan kecenderungan Anda</p></div></div></article>
                    </div>

                    <div class="mt-4 flex flex-wrap gap-3">@if ($unfinished)<a href="{{ route('assessments.questionnaire', $unfinished) }}" class="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-brand-600/20 transition hover:-translate-y-0.5 hover:bg-brand-700 active:scale-[.98]">Lanjutkan tes <x-heroicon-o-arrow-right class="h-4 w-4" /></a>@else<a href="{{ route('assessments.create') }}" class="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-brand-600/20 transition hover:-translate-y-0.5 hover:bg-brand-700 active:scale-[.98]">Mulai tes <x-heroicon-o-arrow-right class="h-4 w-4" /></a>@endif<a href="{{ route('assessments.index') }}" class="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-ink-700 shadow-sm shadow-ink-950/10 transition hover:bg-brand-50 dark:bg-white/[.08] dark:text-porcelain-100 dark:hover:bg-white/[.13]">Riwayat tes <x-heroicon-o-clock class="h-4 w-4" /></a></div>

                    <div class="mt-auto grid grid-cols-3 gap-3 pt-5">@foreach ([['label'=>'Tes selesai','value'=>$totalCompleted,'unit'=>'sesi','icon'=>'clipboard-document-check','tone'=>'brand'],['label'=>'Program studi','value'=>$programCount,'unit'=>'prodi','icon'=>'academic-cap','tone'=>'emerald'],['label'=>'Pernyataan','value'=>$questionCount,'unit'=>'butir','icon'=>'sparkles','tone'=>'violet']] as $stat)<article class="rounded-xl border border-brand-100 bg-white/90 p-3.5 shadow-sm shadow-ink-950/5 dark:border-white/10 dark:bg-white/[.06]"><span @class(['flex h-9 w-9 items-center justify-center rounded-xl','bg-brand-50 text-brand-600 dark:bg-brand-500/15 dark:text-brand-200'=>$stat['tone']==='brand','bg-emerald-50 text-emerald-600 dark:bg-emerald-400/15 dark:text-emerald-200'=>$stat['tone']==='emerald','bg-violet-50 text-violet-600 dark:bg-violet-400/15 dark:text-violet-200'=>$stat['tone']==='violet'])><x-dynamic-component :component="'heroicon-o-'.$stat['icon']" class="h-4 w-4" /></span><p class="mt-3 font-mono text-2xl font-bold text-ink-900 dark:text-porcelain-50">{{ $stat['value'] }}</p><p class="mt-0.5 text-[11px] leading-tight text-ink-600 dark:text-porcelain-300/70">{{ $stat['label'] }}<span class="mt-1 block text-[10px]">• {{ $stat['unit'] }}</span></p></article>@endforeach</div>
                </div>
            </section>

            <section class="dashboard-enter dashboard-enter-2 flex min-h-[32rem] flex-col gap-4 lg:min-h-0">
                <article class="flex min-h-0 flex-1 flex-col rounded-[1.5rem] border border-black/5 bg-white p-5 shadow-xl shadow-ink-950/[.04] dark:border-white/10 dark:bg-ink-900/60"><div class="flex items-start justify-between gap-3"><div><p class="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-brand-600 dark:text-brand-300">Profil tes terakhir</p><h2 class="mt-1 text-base font-bold tracking-tight text-ink-900 dark:text-porcelain-50">Sebaran RIASEC Anda</h2></div><span class="rounded-lg bg-brand-50 px-3 py-1 font-mono text-xs font-bold text-brand-700 dark:bg-brand-500/10 dark:text-brand-200">{{ $totalCompleted }} sesi</span></div>@if ($riasecDistribution !== [])<div class="min-h-0 flex-1 pt-2"><canvas data-assessment-history-chart='@json($riasecDistribution)'></canvas></div>@else<div class="mt-4 flex flex-1 items-center justify-center rounded-xl bg-porcelain-50 px-5 text-center text-sm text-ink-500 dark:bg-ink-950/40 dark:text-porcelain-300/70">Selesaikan tes pertama untuk melihat profil RIASEC Anda.</div>@endif</article>
                <article class="dashboard-enter dashboard-enter-3 flex h-48 flex-none flex-col overflow-hidden rounded-[1.25rem] border border-black/5 bg-white shadow-sm shadow-ink-950/5 dark:border-white/10 dark:bg-ink-900/60"><div class="flex items-start justify-between px-5 pt-4"><div><p class="font-mono text-[9px] font-bold uppercase tracking-[.16em] text-brand-600 dark:text-brand-300">Sesi terbaru</p><h2 class="mt-1 text-sm font-bold text-ink-900 dark:text-porcelain-50">Riwayat rekomendasi</h2></div><a href="{{ route('assessments.index') }}" class="text-xs font-bold text-brand-600 dark:text-brand-300">{{ $recentHistory->count() > 2 ? 'Lihat selengkapnya' : 'Lihat semua' }}</a></div>@if ($recentHistory->isNotEmpty())<div class="mt-2 space-y-2 px-5">@foreach ($recentHistory->take(2) as $index => $assessment)<a href="{{ route('assessments.result', $assessment) }}" class="flex h-12 items-center gap-3 rounded-xl border border-brand-100 bg-white px-3 shadow-sm shadow-ink-950/5 transition hover:-translate-y-0.5 hover:border-brand-300 dark:border-white/10 dark:bg-ink-900"><span @class(['flex h-8 w-8 shrink-0 items-center justify-center rounded-lg font-mono text-[10px] font-bold text-white', 'bg-ink-900' => $index === 0, 'bg-brand-600' => $index === 1])>{{ $assessment->holland_code }}</span><span class="min-w-0 flex-1"><span class="block truncate text-xs font-bold text-ink-800 dark:text-porcelain-100">{{ $assessment->recommendedProgram?->full_name ?? 'Rekomendasi tidak tersedia' }}</span><span class="flex items-center gap-1 text-[10px] text-ink-500 dark:text-porcelain-300/70"><x-heroicon-o-calendar class="h-3 w-3" /> {{ $assessment->completed_at?->translatedFormat('d M Y') }}</span></span><x-heroicon-o-chevron-right class="h-4 w-4 shrink-0 text-ink-400" /></a>@endforeach</div>@else<div class="flex flex-1 items-center px-5 text-sm text-ink-500 dark:text-porcelain-300/70">Belum ada sesi selesai.</div>@endif</article>
            </section>

        </div>
    </div>
</x-app-layout>
